<?php

namespace AppBundle\Repository\ORM;

use Doctrine\ORM\EntityRepository;

/**
 * ImageTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageTagRepository extends EntityRepository
{
}
