<?php

namespace AppBundle\Repository\ORM;

use AppBundle\Entity\ImageTag;
use AppBundle\Repository\Interfaces\ImageTagRepositoryInterface;
use Doctrine\ORM\EntityRepository;

/**
 * ImageTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageTagRepository extends EntityRepository implements ImageTagRepositoryInterface
{
    public function findAllTagNames()
    {
        $qb = $this->createQueryBuilder('it')
            ->select('it.name')
            ;

        return $qb->getQuery()->getArrayResult();
    }
}
