services:
    app.repository.orm.image_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Image

    app.manager.image_manager:
        class: AppBundle\Manager\ImageManager
        arguments:
            - "@app.repository.orm.image_repository"

    image.manager:
        alias: app.manager.image_manager

    app.doctrine.listener:
        class: AppBundle\EventListener\UniqueImageTag
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }

    app.form.handler.image_form_handler:
        class: AppBundle\Form\Handler\ImageFormHandler
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@form.factory"

    image.form.handler:
        alias: app.form.handler.image_form_handler